//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidWasteTaxesUserApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidWasteTaxesUserApplication.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Waste Tax Management is a simple and useful application completely developed for Windows Phone 8 that gives you the opportunity to check your obligations on Waste Taxes. The application allows you to check your Current Year Waste Taxes, your Previous Year Waste Taxes, your Interests Taxes and your Specific Waste Taxes.
        ///Solid Waste Taxes also gives you the oppurtunity to make requests for the transportation of Specific Waste from your home or office, such as Medical Waste or Chemical Waste!.
        /// </summary>
        public static string AboutPageContent {
            get {
                return ResourceManager.GetString("AboutPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulator.
        /// </summary>
        public static string AccumulatorLabel {
            get {
                return ResourceManager.GetString("AccumulatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Waste.
        /// </summary>
        public static string AnimalWasteLabel {
            get {
                return ResourceManager.GetString("AnimalWasteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Taxes Information Application.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date :.
        /// </summary>
        public static string CardExpiryDate {
            get {
                return ResourceManager.GetString("CardExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card holder name :.
        /// </summary>
        public static string CardHolderNameLabel {
            get {
                return ResourceManager.GetString("CardHolderNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Information.
        /// </summary>
        public static string CardInformationLabel {
            get {
                return ResourceManager.GetString("CardInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type :.
        /// </summary>
        public static string CardTypeLabel {
            get {
                return ResourceManager.GetString("CardTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Waste.
        /// </summary>
        public static string ChemicalWasteLabel {
            get {
                return ResourceManager.GetString("ChemicalWasteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose waste type!.
        /// </summary>
        public static string ChooseSpecificWasteLabel {
            get {
                return ResourceManager.GetString("ChooseSpecificWasteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ConfigurationLabel {
            get {
                return ResourceManager.GetString("ConfigurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction.
        /// </summary>
        public static string ConstructionLabel {
            get {
                return ResourceManager.GetString("ConstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please,enter credit card holder name!.
        /// </summary>
        public static string CreditCardHolderNameValidationMessage {
            get {
                return ResourceManager.GetString("CreditCardHolderNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card No. :.
        /// </summary>
        public static string CreditCardNumberLabel {
            get {
                return ResourceManager.GetString("CreditCardNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please, enter credit card number!.
        /// </summary>
        public static string CreditCardNumberValidationMessage {
            get {
                return ResourceManager.GetString("CreditCardNumberValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year Taxes :.
        /// </summary>
        public static string CurrentYearTaxesLabel {
            get {
                return ResourceManager.GetString("CurrentYearTaxesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        public static string ElectronicsLabel {
            get {
                return ResourceManager.GetString("ElectronicsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry !Something went wrong !.
        /// </summary>
        public static string FailureInformationLabel {
            get {
                return ResourceManager.GetString("FailureInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plase,enter your full name !.
        /// </summary>
        public static string FullNameMessage {
            get {
                return ResourceManager.GetString("FullNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your personal identity number !.
        /// </summary>
        public static string IdentityNumberMessage {
            get {
                return ResourceManager.GetString("IdentityNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests :.
        /// </summary>
        public static string InterestAmoutLabel {
            get {
                return ResourceManager.GetString("InterestAmoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Waste.
        /// </summary>
        public static string MedicalWasteLabel {
            get {
                return ResourceManager.GetString("MedicalWasteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your personal data in Settings!.
        /// </summary>
        public static string NoPersonalDataInSettings {
            get {
                return ResourceManager.GetString("NoPersonalDataInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Waste Taxes Information page !.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Taxes.
        /// </summary>
        public static string PayButtonLabel {
            get {
                return ResourceManager.GetString("PayButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PaymentHeaderLabel {
            get {
                return ResourceManager.GetString("PaymentHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment was successful!.
        /// </summary>
        public static string PaymentMadeLabel {
            get {
                return ResourceManager.GetString("PaymentMadeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Personal Identity Number Required !.
        /// </summary>
        public static string PersonalIdentityNumberRequiredLabel {
            get {
                return ResourceManager.GetString("PersonalIdentityNumberRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Name Required !.
        /// </summary>
        public static string PersonFullNameRequiredLabel {
            get {
                return ResourceManager.GetString("PersonFullNameRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Years Taxes :.
        /// </summary>
        public static string PreviousYearsTaxestLabel {
            get {
                return ResourceManager.GetString("PreviousYearsTaxestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageLabel {
            get {
                return ResourceManager.GetString("SettingsPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved!.
        /// </summary>
        public static string SettingsSavedLabel {
            get {
                return ResourceManager.GetString("SettingsSavedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Waste Information.
        /// </summary>
        public static string SolidWasteInformationLabel {
            get {
                return ResourceManager.GetString("SolidWasteInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Waste Taxes.
        /// </summary>
        public static string SolidWasteTaxesHeader {
            get {
                return ResourceManager.GetString("SolidWasteTaxesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Waste Request.
        /// </summary>
        public static string SpecificWasteHeaderLabel {
            get {
                return ResourceManager.GetString("SpecificWasteHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Waste Request.
        /// </summary>
        public static string SpecificWasteRequest {
            get {
                return ResourceManager.GetString("SpecificWasteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Waste Request.
        /// </summary>
        public static string SpecificWasteRequestHeader {
            get {
                return ResourceManager.GetString("SpecificWasteRequestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Waste Request.
        /// </summary>
        public static string SpecificWasteRequestPageLevel {
            get {
                return ResourceManager.GetString("SpecificWasteRequestPageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  request sent!.
        /// </summary>
        public static string SpecificWasteRequestSentLabel {
            get {
                return ResourceManager.GetString("SpecificWasteRequestSentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Waste Taxes :.
        /// </summary>
        public static string SpecificWasteTaxesLabel {
            get {
                return ResourceManager.GetString("SpecificWasteTaxesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes Information.
        /// </summary>
        public static string TaxesInformation {
            get {
                return ResourceManager.GetString("TaxesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes Information.
        /// </summary>
        public static string TaxesInformationHeaderLabel {
            get {
                return ResourceManager.GetString("TaxesInformationHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes Information.
        /// </summary>
        public static string TaxesInformationPageLabel {
            get {
                return ResourceManager.GetString("TaxesInformationPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Debt :.
        /// </summary>
        public static string TotalDebtLabel {
            get {
                return ResourceManager.GetString("TotalDebtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.........{0}%.
        /// </summary>
        public static string WaitingLabel {
            get {
                return ResourceManager.GetString("WaitingLabel", resourceCulture);
            }
        }
    }
}
